### ISSUE TITLE
Ops20 - Missing URL on Functions for App Insights status-xxx

### ISSUE THREAD

**Issue by ghost** [microsoft/ignite-learning-paths-training-ops#38] opened 2019-11-28 01:22 UTC
There is no URL on the main screen anywhere that i can see anywhere but there was a pop up that says "Live metrics public IP addresses have changed. You may need to update your service firewall rules to continue using live metrics."

Link provided on Azure: https://docs.microsoft.com/en-us/azure/azure-monitor/app/ip-addresses#outgoing-ports
![URL issue for Ops20 demo](https://user-images.githubusercontent.com/51760646/69769618-6c3e0280-113a-11ea-8831-83defcbf03d9.png)
@jasonhand

**Comment by jasonhand** [comment] 2020-01-14 14:31
Unable to reproduce this message. Closing for now but please submit again if it happens again.

**Closed as completed by jasonhand** 2020-01-14 14:31 UTC
Labels: documentation
